#pragma once

#define ERROR_WRITE_PPM_HEADER 10
#define ERROR_CANVAS_DEMO_FILE_OPEN 11
#define ERROR_MATRIX_NONINVERTIBLE 12
#define ERROR_GROW_INTERSECTION_LIST 13
#define ERROR_GROW_WORLD_POINT_LIGHTS_LIST 14
#define ERROR_GROW_WORLD_SHAPES_LIST 15

